### ISSUE TITLE
On ETH pool.binance.com miner add .eth1.0 to worker name

### ISSUE THREAD

**Issue by extrimexxx** [develsoftware/GMinerRelease#158]
`miner.exe --algo ethash --server ethash.poolbinance.com:3333 --proto proxy --user username.rig01 --pass x`
on pool showed like this: `rig01.eth1.0 `
if change `--proto proxy` to `--proto stratum` showed `rig01`
on other phoenix miner in proto eth-proxy is no such bug

**Comment by heri16** [comment]
I’m having the same issue here

**Comment by stevenpollack** [comment]
same issue here.

**Comment by emmanuhell** [comment]
hey guys, working fine for me with the following .bat
miner.exe --algo ethash --server ethash.poolbinance.com:1800 --user XXX01 pause

**Comment by thaneb** [comment]
Emmanuhell, what's your shares server's acceptation latency ? (question not related to gminer, but to binance pool)

**Comment by emmanuhell** [comment]
Hello ThAnEb,
I cannot give you a good answer at the moment as I am just in the process
of testing different miners. I am doing my tests on a laptop with a Nvidia
1070. It s ok to do try different settings and play around but there is no
real validity in the mining datas because a laptop is definitely the worst
computer to mine (no management of energy input and limited overclocking
for the GPU as well).  I am planning to use Binance Pool so I will try to
remember to update this post when my rig will be set and running...

**Comment by wjd000** [comment]
Why I can't find my miner on poolbinance？
I run the code "miner.exe --algo ethash --server ethash.poolbinance.com:3333 --proto stratum --user username.workerG --pass x"  on gminer_2_47_windows64

**Comment by stevenpollack** [comment]
Because binance is taking forever to respond to shares. Use nbminer,
instead.

**Comment by emmanuhell** [comment]
This is the command line I use to start Gminer on the Binance Pool:

miner.exe --algo ethash --server ethash.poolbinance.com:1800 --user
YourUserName
pause

Give it a try...

**Comment by emmanuhell** [comment]
Useless comment, another keyboard troll with no brain I guess....

**Comment by extrimexxx** [comment]
Fixed in 2.50 release, added `--worker` parameter to specify worker name for ETH pools thats doesn't support wallet.worker notation
